/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/v1/meta": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Meta */
        get: operations["meta_api_v1_meta_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Health */
        get: operations["health_api_v1_health_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/metrics": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Metrics View */
        get: operations["metrics_view_api_v1_metrics_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/overview": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Overview */
        get: operations["overview_api_v1_overview_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/incidents": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Incidents */
        get: operations["incidents_api_v1_incidents_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/incidents/{incident_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Incident */
        get: operations["incident_api_v1_incidents__incident_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/incidents/{incident_id}/weather": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Incident Weather */
        get: operations["incident_weather_api_v1_incidents__incident_id__weather_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/incidents/{incident_id}/knowledge": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Incident Knowledge
         * @description Data Time Machine: what ATLAS knew about this incident at a past instant.
         */
        get: operations["incident_knowledge_api_v1_incidents__incident_id__knowledge_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/changes": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Changes */
        get: operations["changes_api_v1_changes_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/layers/earthquakes": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Layer Earthquakes */
        get: operations["layer_earthquakes_api_v1_layers_earthquakes_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/layers/fires/grid": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Layer Fire Grid */
        get: operations["layer_fire_grid_api_v1_layers_fires_grid_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/layers/fires/detections": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Layer Fire Points */
        get: operations["layer_fire_points_api_v1_layers_fires_detections_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/layers/fires/clusters": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Layer Fire Clusters */
        get: operations["layer_fire_clusters_api_v1_layers_fires_clusters_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/geo/countries": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Countries */
        get: operations["countries_api_v1_geo_countries_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/search": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Search */
        get: operations["search_api_v1_search_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/sources": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Sources */
        get: operations["sources_api_v1_sources_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/sources/{source_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Source */
        get: operations["source_api_v1_sources__source_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/sources/{source_id}/sync": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Source Sync */
        post: operations["source_sync_api_v1_sources__source_id__sync_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/storage": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Storage */
        get: operations["storage_api_v1_storage_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/storage/cache/clear": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Clear Cache */
        post: operations["clear_cache_api_v1_storage_cache_clear_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/stream": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Stream */
        get: operations["stream_api_v1_stream_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** ChangeOut */
        ChangeOut: {
            /** Id */
            id: number | null;
            /** Incident Id */
            incident_id: string;
            /** At */
            at: string;
            /** Kind */
            kind: string;
            /** Field */
            field?: string | null;
            /** Old Value */
            old_value?: string | null;
            /** New Value */
            new_value?: string | null;
            /** Source */
            source?: string | null;
            /** Observation Id */
            observation_id?: string | null;
            /** Summary */
            summary: string;
            /** Significance */
            significance: number;
        };
        /** Citation */
        Citation: {
            /** Source Id */
            source_id: string;
            /** Name */
            name: string;
            /** Provider */
            provider: string;
            /** Attribution */
            attribution: string;
            /** License */
            license: string;
            /** License Url */
            license_url: string;
            /** Contributed */
            contributed: string;
            /** Retrieved At */
            retrieved_at: string | null;
            /** Source Updated At */
            source_updated_at: string | null;
            /** Url */
            url: string | null;
            /** Reliability */
            reliability: string;
        };
        /**
         * Columnar
         * @description Compact column-oriented payload for map layers (one array per field).
         */
        Columnar: {
            /** Count */
            count: number;
            /** Columns */
            columns: {
                [key: string]: unknown[];
            };
            /** Generated At */
            generated_at: string;
            /** Attribution */
            attribution: string[];
            /** Note */
            note?: string | null;
        };
        /** Confidence */
        Confidence: {
            /** Score */
            score: number;
            /**
             * Label
             * @enum {string}
             */
            label: "low" | "moderate" | "high" | "very high";
            /** Components */
            components: components["schemas"]["ConfidenceComponent"][];
            /**
             * Method
             * @default atlas-confidence-heuristic-v1
             */
            method: string;
            /**
             * Note
             * @default Heuristic summary of source count, agreement, review status and recency. It is not a calibrated probability.
             */
            note: string;
        };
        /** ConfidenceComponent */
        ConfidenceComponent: {
            /** Name */
            name: string;
            /** Score */
            score: number;
            /** Weight */
            weight: number;
            /** Detail */
            detail: string;
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /** HazardCount */
        HazardCount: {
            /** Hazard */
            hazard: string;
            /** Label */
            label: string;
            /** Active */
            active: number;
            /** Monitoring */
            monitoring: number;
            /** Max Severity */
            max_severity: number;
        };
        /** IncidentDetail */
        IncidentDetail: {
            /** Id */
            id: string;
            /** Hazard */
            hazard: string;
            /** Hazard Label */
            hazard_label: string;
            /** Title */
            title: string;
            /** Status */
            status: string;
            /** Lat */
            lat: number | null;
            /** Lon */
            lon: number | null;
            /** Bbox */
            bbox: number[] | null;
            /** Started At */
            started_at: string;
            /** Updated At */
            updated_at: string;
            /** Last Observation At */
            last_observation_at: string;
            /** Ended At */
            ended_at?: string | null;
            severity: components["schemas"]["Severity"];
            confidence: components["schemas"]["Confidence"];
            /** Headline */
            headline: components["schemas"]["Metric"][];
            /** Country Iso3 */
            country_iso3: string | null;
            /** Country Name */
            country_name: string | null;
            place: components["schemas"]["PlaceOut"] | null;
            /** Source Count */
            source_count: number;
            /** Sources */
            sources: string[];
            /**
             * Change Count
             * @default 0
             */
            change_count: number;
            last_change?: components["schemas"]["ChangeOut"] | null;
            /** Geometry */
            geometry: {
                [key: string]: unknown;
            } | null;
            /** Track */
            track: {
                [key: string]: unknown;
            }[];
            /** Observations */
            observations: components["schemas"]["ObservationOut"][];
            /** Changes */
            changes: components["schemas"]["ChangeOut"][];
            /** Citations */
            citations: components["schemas"]["Citation"][];
            /** Official Links */
            official_links: components["schemas"]["OfficialLink"][];
            /** Nearby Places */
            nearby_places: components["schemas"]["PlaceOut"][];
            /** Related */
            related: components["schemas"]["RelatedIncident"][];
            /** Limitations */
            limitations: string[];
        };
        /** IncidentList */
        IncidentList: {
            /** Items */
            items: components["schemas"]["IncidentSummary"][];
            /** Total */
            total: number;
            /** Generated At */
            generated_at: string;
        };
        /** IncidentSummary */
        IncidentSummary: {
            /** Id */
            id: string;
            /** Hazard */
            hazard: string;
            /** Hazard Label */
            hazard_label: string;
            /** Title */
            title: string;
            /** Status */
            status: string;
            /** Lat */
            lat: number | null;
            /** Lon */
            lon: number | null;
            /** Bbox */
            bbox: number[] | null;
            /** Started At */
            started_at: string;
            /** Updated At */
            updated_at: string;
            /** Last Observation At */
            last_observation_at: string;
            /** Ended At */
            ended_at?: string | null;
            severity: components["schemas"]["Severity"];
            confidence: components["schemas"]["Confidence"];
            /** Headline */
            headline: components["schemas"]["Metric"][];
            /** Country Iso3 */
            country_iso3: string | null;
            /** Country Name */
            country_name: string | null;
            place: components["schemas"]["PlaceOut"] | null;
            /** Source Count */
            source_count: number;
            /** Sources */
            sources: string[];
            /**
             * Change Count
             * @default 0
             */
            change_count: number;
            last_change?: components["schemas"]["ChangeOut"] | null;
        };
        /** Metric */
        Metric: {
            /** Key */
            key: string;
            /** Label */
            label: string;
            /** Value */
            value: number | string | boolean | null;
            /** Unit */
            unit?: string | null;
            provenance: components["schemas"]["Provenance"];
            /** Source */
            source?: string | null;
            /** Method */
            method?: string | null;
            /** Observed At */
            observed_at?: string | null;
            /** Note */
            note?: string | null;
        };
        /** ObservationOut */
        ObservationOut: {
            /** Id */
            id: string;
            /** Source */
            source: string;
            /** Source Name */
            source_name: string;
            /** External Id */
            external_id: string;
            /** Hazard */
            hazard: string;
            /** Title */
            title: string;
            /** Lat */
            lat: number | null;
            /** Lon */
            lon: number | null;
            /** Depth Km */
            depth_km: number | null;
            /** Magnitude */
            magnitude: number | null;
            /** Magnitude Unit */
            magnitude_unit: string | null;
            /** Alert Level */
            alert_level: string | null;
            /** Status */
            status: string | null;
            /** Event Time */
            event_time: string;
            /** End Time */
            end_time: string | null;
            /** Source Updated At */
            source_updated_at: string | null;
            /** First Seen At */
            first_seen_at: string;
            /** Last Seen At */
            last_seen_at: string;
            /** Url */
            url: string | null;
            /** Description */
            description: string | null;
            /** Metrics */
            metrics: {
                [key: string]: unknown;
            };
            /** Version */
            version: number;
        };
        /** OfficialLink */
        OfficialLink: {
            /** Label */
            label: string;
            /** Url */
            url: string;
            /** Authority */
            authority: string;
        };
        /** Overview */
        Overview: {
            /** Generated At */
            generated_at: string;
            /** Incidents Active */
            incidents_active: number;
            /** Incidents Monitoring */
            incidents_monitoring: number;
            /** By Hazard */
            by_hazard: components["schemas"]["HazardCount"][];
            /** Severity Histogram */
            severity_histogram: {
                [key: string]: number;
            };
            /** Earthquakes 24H */
            earthquakes_24h: number;
            /** Earthquakes 24H Max Mag */
            earthquakes_24h_max_mag: number | null;
            /** Fire Detections 24H */
            fire_detections_24h: number;
            /** Fire Clusters */
            fire_clusters: number;
            /** Active Cyclones */
            active_cyclones: number;
            /** Recent Changes */
            recent_changes: components["schemas"]["ChangeOut"][];
            /** Sources */
            sources: components["schemas"]["SourceHealth"][];
            /** Observations Total */
            observations_total: number;
        };
        /** PlaceOut */
        PlaceOut: {
            /** Name */
            name: string;
            /** Country */
            country?: string | null;
            /** Country Iso3 */
            country_iso3?: string | null;
            /** Lat */
            lat: number;
            /** Lon */
            lon: number;
            /** Population */
            population?: number | null;
            /** Distance Km */
            distance_km: number;
            /** Bearing Deg */
            bearing_deg: number;
            /** Compass */
            compass: string;
            /** Description */
            description: string;
            /** Offshore Km */
            offshore_km?: number | null;
            /** Admin1 */
            admin1?: string | null;
        };
        /**
         * Provenance
         * @description How a value came to exist. Surfaced on every metric in the interface.
         * @enum {string}
         */
        Provenance: "real" | "derived" | "model" | "simulation" | "unavailable";
        /** RelatedIncident */
        RelatedIncident: {
            /** Id */
            id: string;
            /** Title */
            title: string;
            /** Hazard */
            hazard: string;
            /** Severity Level */
            severity_level: number;
            /** Status */
            status: string;
            /** Distance Km */
            distance_km: number;
            /** Started At */
            started_at: string;
            /** Relation */
            relation: string;
        };
        /** Severity */
        Severity: {
            /** Level */
            level: number;
            /** Label */
            label: string;
            /** Basis */
            basis: string;
            /**
             * Method
             * @default atlas-severity-v1
             */
            method: string;
            /** @default derived */
            provenance: components["schemas"]["Provenance"];
        };
        /** SourceHealth */
        SourceHealth: {
            /** Id */
            id: string;
            /** Name */
            name: string;
            /** Status */
            status: string;
            /** Last Ok */
            last_ok: string | null;
            /** Data Age S */
            data_age_s: number | null;
        };
        /** SourceStatus */
        SourceStatus: {
            /** Id */
            id: string;
            /** Meta */
            meta: {
                [key: string]: unknown;
            };
            /** Enabled */
            enabled: boolean;
            /** Disabled Reason */
            disabled_reason: string | null;
            /** Status */
            status: string;
            /** Last Attempt */
            last_attempt: string | null;
            /** Last Success */
            last_success: string | null;
            /** Last Error */
            last_error: string | null;
            /** Data Time */
            data_time: string | null;
            /** Data Age S */
            data_age_s: number | null;
            /** Latency Ms P50 */
            latency_ms_p50: number | null;
            /** Stored Records */
            stored_records: number;
            /** Runs 24H */
            runs_24h: number;
            /** Errors 24H */
            errors_24h: number;
            /** Bytes 24H */
            bytes_24h: number;
            /** Jobs */
            jobs?: {
                [key: string]: unknown;
            }[];
            /** Recent Runs */
            recent_runs?: components["schemas"]["SyncRunOut"][];
        };
        /** SyncRunOut */
        SyncRunOut: {
            /** Id */
            id: number;
            /** Started At */
            started_at: string;
            /** Finished At */
            finished_at: string | null;
            /** Status */
            status: string;
            /** Records Received */
            records_received: number;
            /** Records Accepted */
            records_accepted: number;
            /** Records Rejected */
            records_rejected: number;
            /** Records Changed */
            records_changed: number;
            /** Bytes */
            bytes: number;
            /** Latency Ms */
            latency_ms: number | null;
            /** From Cache */
            from_cache: boolean;
            /** Stale */
            stale: boolean;
            /** Data Time */
            data_time: string | null;
            /** Message */
            message: string | null;
        };
        /** ValidationError */
        ValidationError: {
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
            /** Input */
            input?: unknown;
            /** Context */
            ctx?: Record<string, never>;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    meta_api_v1_meta_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
        };
    };
    health_api_v1_health_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
        };
    };
    metrics_view_api_v1_metrics_get: {
        parameters: {
            query?: {
                logs?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    overview_api_v1_overview_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Overview"];
                };
            };
        };
    };
    incidents_api_v1_incidents_get: {
        parameters: {
            query?: {
                status?: string | null;
                hazard?: string | null;
                min_severity?: number;
                q?: string | null;
                bbox?: string | null;
                since?: string | null;
                until?: string | null;
                country?: string | null;
                sort?: string;
                limit?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["IncidentList"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    incident_api_v1_incidents__incident_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                incident_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["IncidentDetail"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    incident_weather_api_v1_incidents__incident_id__weather_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                incident_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    incident_knowledge_api_v1_incidents__incident_id__knowledge_get: {
        parameters: {
            query?: {
                at?: string | null;
            };
            header?: never;
            path: {
                incident_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    changes_api_v1_changes_get: {
        parameters: {
            query?: {
                since?: string | null;
                min_significance?: number;
                limit?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    layer_earthquakes_api_v1_layers_earthquakes_get: {
        parameters: {
            query?: {
                hours?: number;
                min_mag?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Columnar"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    layer_fire_grid_api_v1_layers_fires_grid_get: {
        parameters: {
            query?: {
                res?: number;
                hours?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Columnar"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    layer_fire_points_api_v1_layers_fires_detections_get: {
        parameters: {
            query?: {
                bbox?: string | null;
                hours?: number;
                limit?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Columnar"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    layer_fire_clusters_api_v1_layers_fires_clusters_get: {
        parameters: {
            query?: {
                min_detections?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    countries_api_v1_geo_countries_get: {
        parameters: {
            query?: {
                res?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    search_api_v1_search_get: {
        parameters: {
            query: {
                q: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    sources_api_v1_sources_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SourceStatus"][];
                };
            };
        };
    };
    source_api_v1_sources__source_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                source_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SourceStatus"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    source_sync_api_v1_sources__source_id__sync_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                source_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    storage_api_v1_storage_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
        };
    };
    clear_cache_api_v1_storage_cache_clear_post: {
        parameters: {
            query?: {
                source?: string | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    stream_api_v1_stream_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
        };
    };
}
