/**
 * Exports. Every export carries provenance and the attribution required by each source's
 * licence — values are never exported without saying where they came from.
 */
import type { IncidentDetail } from "./api";
import { coord, metricValue, utcFull } from "./format";
import { PROVENANCE_META } from "./hazards";

function download(name: string, mime: string, body: string) {
  const blob = new Blob([body], { type: mime });
  const url = URL.createObjectURL(blob);
  const a = document.createElement("a");
  a.href = url;
  a.download = name;
  document.body.appendChild(a);
  a.click();
  a.remove();
  setTimeout(() => URL.revokeObjectURL(url), 2000);
}

const stamp = () => new Date().toISOString().replace(/[:.]/g, "-").slice(0, 19);

export function briefMarkdown(d: IncidentDetail): string {
  const line = "─".repeat(48);
  const lines: string[] = [
    "# ATLAS INCIDENT BRIEF",
    line,
    "",
    `**${d.title}**  `,
    `\`${d.id}\` · ${d.hazard_label} · status **${d.status}**`,
    "",
    "## Location",
    `${d.place?.description ?? "—"}${d.country_name ? ` · ${d.country_name}` : ""}  `,
    `${coord(d.lat, d.lon, 3)}`,
    "",
    "## Time",
    `Onset: ${utcFull(d.started_at)}  `,
    `Latest observation: ${utcFull(d.last_observation_at)}  `,
    `Brief generated: ${utcFull(new Date().toISOString())}`,
    "",
    "## Assessment",
    `Severity: **${d.severity.label} (${d.severity.level}/5)** — ${d.severity.basis}  `,
    `Method: ${d.severity.method} (ATLAS-derived ordinal scale; not an impact estimate)`,
    "",
    `Confidence: **${d.confidence.label}** (${Math.round(d.confidence.score * 100)}/100, ${d.confidence.method}; heuristic, not a probability)`,
    ...d.confidence.components.map((c) => `- ${c.name}: ${Math.round(c.score * 100)} — ${c.detail}`),
    "",
    "## Key observations",
    "| Metric | Value | Provenance | Source |",
    "|---|---|---|---|",
    ...d.headline.map(
      (m) => `| ${m.label} | ${metricValue(m.value, m.unit)} | ${PROVENANCE_META[m.provenance as keyof typeof PROVENANCE_META]?.label ?? m.provenance} | ${m.source ?? "—"} |`,
    ),
    "",
    "## Recent updates",
    ...(d.changes.length ? d.changes.slice(0, 12).map((c) => `- ${utcFull(c.at)} — ${c.summary}`) : ["- No changes recorded."]),
    "",
    "## Official sources",
    ...d.official_links.map((l) => `- [${l.label}](${l.url}) — ${l.authority}`),
    "",
    "## Limitations",
    ...d.limitations.map((l) => `- ${l}`),
    "",
    "## Sources & attribution",
    ...d.citations.map((c) => `- **${c.name}** (${c.license}) — ${c.attribution}${c.retrieved_at ? ` · retrieved ${utcFull(c.retrieved_at)}` : ""}`),
    "",
    "_Generated by ATLAS, an open research tool. Not an official alert. Follow your national authorities._",
  ];
  return lines.join("\n");
}

export function exportBrief(d: IncidentDetail) {
  download(`${d.id}_brief_${stamp()}.md`, "text/markdown;charset=utf-8", briefMarkdown(d));
}

export function exportJson(d: IncidentDetail) {
  const body = {
    exported_at: new Date().toISOString(),
    generator: "ATLAS",
    notice: "Values carry provenance (real/derived/model). See citations for licences.",
    incident: d,
  };
  download(`${d.id}_${stamp()}.json`, "application/json", JSON.stringify(body, null, 2));
}

export function exportGeoJson(d: IncidentDetail) {
  const features: GeoJSON.Feature[] = [];
  if (d.lat != null && d.lon != null) {
    features.push({
      type: "Feature",
      geometry: { type: "Point", coordinates: [d.lon, d.lat] },
      properties: {
        id: d.id,
        title: d.title,
        hazard: d.hazard,
        status: d.status,
        severity_level: d.severity.level,
        severity_basis: d.severity.basis,
        started_at: d.started_at,
        last_observation_at: d.last_observation_at,
        sources: d.sources.join(", "),
        role: "incident",
      },
    });
  }
  for (const f of (d.geometry?.features as GeoJSON.Feature[] | undefined) ?? []) features.push(f);
  const track = (d.track ?? []) as { time: string; lat: number; lon: number; kind?: string }[];
  if (track.length > 1) {
    features.push({
      type: "Feature",
      geometry: { type: "LineString", coordinates: track.map((p) => [p.lon, p.lat]) },
      properties: { role: "track", times: track.map((p) => p.time).join(",") },
    });
  }
  const fc = {
    type: "FeatureCollection",
    features,
    attribution: d.citations.map((c) => c.attribution),
    exported_at: new Date().toISOString(),
  };
  download(`${d.id}_${stamp()}.geojson`, "application/geo+json", JSON.stringify(fc, null, 2));
}
